DROP DATABASE IF EXISTS trivia;
DROP USER IF EXISTS felizer;
CREATE DATABASE trivia;
CREATE USER felizer WITH ENCRYPTED PASSWORD 'felizer';
GRANT ALL PRIVILEGES ON DATABASE trivia TO felizer;
ALTER USER felizer CREATEDB;
ALTER USER felizer WITH SUPERUSER;